import Button from "@/components/ui/buttons/button";
import SectionLabel from "@/components/ui/labels/section";
import Heading from "@/components/ui/typography/heading";
import Paragraph from "@/components/ui/typography/paragraph";

export default function ReferralsSection() {
  return (
    <section className="bg-beige pb-[6.563rem] rounded-b-[4rem] pt-10">
      <div className="container mx-auto">
        <div className="max-w-[650px] mx-auto flex flex-col gap-8 items-center justify-center text-center">
          <div className="flex flex-col items-center gap-2">
            <SectionLabel>Referrals</SectionLabel>
            <Heading size="medium">Refer traders and earn rewards</Heading>
          </div>
          <Paragraph size="large" className="text-purple-dim max-w-[558px]">
            Hydration is to be shared. Invite users and start accumulating
            referral rewards generated by their future trades. The more volume
            you help onboard, the higher rewards you will be earning.
          </Paragraph>
          <Button role="primary" action={{ href: "/app" }} decoration="arrow">
            Get Your Referral Code
          </Button>
        </div>
      </div>
    </section>
  );
}
